name: saphir
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Certifique-se de que está correto para Dart 3

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  another_flutter_splash_screen: ^1.2.1 # Garantir que essa dependência suporte o SDK atual
  gif: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.11.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: DaysOne
      fonts:
        - asset: assets/fonts/DaysOne.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/saphiricon.png"
